### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by TwixxCustoms** [patorjk/JavaScript-Snake#49]
There isn's any json file included in the github repo. What should such a file contain?

**Comment by patorjk** [comment]
package.json files are related to npm. This project is not an installable library nor does it have any dependenies, so it doesn't need a package.json. Typically a package.json file contains:

1) A list of dependencies for the project/library. 
2) Descriptive information and metadata about a project - mostly so people using npmjs.org can find it.
3) Scripts to run for the project (ie: for testing, for building, etc).

This project doesn't really need any of that, so that's why it doesn't have a package.json.
